<div class="container">
    <div id="contact-row" class="row">
        <div class="col-md-6 col-md-offset-3">
            <?php
            if (isset($response)) {
                echo '<div role="alert" class="alert alert-success"><strong>' . $response . '</strong></div>';
            }
            ?>
            <div class="well well-sm <?php
            if (isset($response)) {
                echo ' hide';
            }
            ?>">
                <form class="form-horizontal" action="contact/send-email" method="post">
                    <fieldset>
                        <legend class="text-center">Kontakt oss</legend>

                        <!-- Name input-->
                        <div class="form-group">
                            <label class="col-md-2 control-label" for="navn">Navn</label>
                            <div class="col-md-10">
                                <input id="navn" name="name" type="text" placeholder="Ditt navn" class="form-control" spellcheck="false" autocomplete="off" autocorrect="off">
                            </div>
                        </div>

                        <!-- Email input-->
                        <div class="form-group">
                            <label class="col-md-2 control-label" for="e-post">E-post</label>
                            <div class="col-md-10">
                                <input id="e-post" name="email" type="text" placeholder="Din e-post" class="form-control" spellcheck="false" autocomplete="off" autocorrect="off">
                            </div>
                        </div>

                        <!-- Message body -->
                        <div class="form-group">
                            <label class="col-md-2 control-label" for="message">Melding</label>
                            <div class="col-md-10">
                                <textarea class="form-control" id="message" name="message" placeholder="Vennligst skriv melding her..." rows="5"></textarea>
                            </div>
                        </div>

                        <!-- Form actions -->
                        <div class="form-group">
                            <div class="col-md-12 text-right">
                                <button type="submit" class="btn btn-success btn-lg" name="submit">Send</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>