<div class="content container">

    <div class="row" id="events">
        <section id="detaljevent">
            <a href="#event">
                <img src="../../public/images/COLOURBOX95430431.jpg">
                <h3>Event</h3>
            </a>
            <h6>08.06.2017</h6>
            <h6>kl 12:00-24:00</h6>
            <a href="https://www.google.no/maps/place/Cafe+Sara/@59.9176068,10.7519658,17z/data=!3m1!4b1!4m5!3m4!1s0x46416e66acf2ba6d:0x6e108cf4f57a3db7!8m2!3d59.9176068!4d10.7541491"><h6>Café Sara</h6></a>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus</p>
        </section>
        <div id="kart">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1999.8759080117252!2d10.751965780677121!3d59.91760678195725!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46416e66acf2ba6d%3A0x6e108cf4f57a3db7!2sCafe+Sara!5e0!3m2!1sno!2sno!4v1495723645386" width="100%" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>

</div>