
<div class="content container">
    <div class="event-filter-collection">
        <div class="event-lead">Filter</div>
        <div class="event-filter-tool">
            <div class="tool-wrapper">
                <label for="tag-filter-option">Tag</label>
                <select id="tag-filter-option" class="tag-slc select-box" name="tag" onchange="javascript:addFilter(event)">
                    <option value=""></option>
                    <?php
                    foreach ($options['tags'] as $tag) {
                        echo '<option value="' . $tag . '">' . $tag . '</option>';
                    }
                    ?>
                </select>
            </div>
            <div class="tool-wrapper">
                <label for = "date-filter-option">Dato</label>
                <select id="date-filter-option" class = "tag-slc select-box" name="date" onchange="javascript:addFilter(event)">
                    <option value = ""></option>
                    <?php
                    foreach ($options['dates'] as $tag) {
                        echo '<option value="' . $tag . '">' . $tag . '</option>';
                    }
                    ?>
                </select>
            </div>
            <div class="tool-wrapper">
                <label for="price-filter-option">Pris t.o.m</label>
                <select id="price-filter-option" class="tag-slc select-box" name="price" onchange="javascript:addFilter(event)">
                    <option value = ""></option>
                    <?php
                    foreach ($options['prices'] as $tag) {
                        echo '<option value="' . $tag . '">' . $tag . '</option>';
                    }
                    ?>
                </select>
            </div>
        </div>
    </div>

    <div id="events"></div>
    <script>
<?php
$row = array();
$temp = array('<div class="row">');
$length = count($events);

for ($i = 0; $i < $length; $i++) {
    $event = $events[$i];
    array_push($temp,
        '<section class="col-md-4 text-left arrangement-section" id="event-' . $event->getId() . '">'
        . '<a href="event/id' . $event->getId() . '">'
        . '<img alt="' . $event->getName() . '" src="' . $event->getImagePath() . '">'
        . '<h2>' . $event->getName() . '</h2>'
        . '</a>'
        . '<div><strong>Dato:</strong> ' . $event->getDate() . '</div>'
        . '<div><strong>Tid:</strong> ' . $event->getTime() . '</div>'
        . '<div><strong>Sted:</strong> <a href="#" onclick="javascript:displayEventLightboxMap(event)" class="location-link">' . $event->getLocation()->getAddress() . ', ' . $event->getLocation()->getZipCode() . ' ' . $event->getLocation()->getCity() . '</a></div>'
        . '<div><strong>Pris:</strong> ' . $event->getPrice() . ' kr</div>'
        . '<div><strong>Arrangør:</strong> ' . $event->getOrganizer()->getName() . '</div>'
        . '<div class="description"> ' . $event->getDescription() . '</div>'
        . '<div class="location-map"> ' . $event->getLocation()->getLocationPath() . '</div>'
        . '</section>'
    );
    if ((($i + 1) % 3) == 0) {
        array_push($temp, '</div>');
        array_push($row, join('', $temp));
        $temp = array('<div class="row">');
    }
}
array_push($temp, '</div>');
array_push($row, join("", $temp));
echo 'var list = [\'' . join('\',\'', $row) . '\'];';
?>
        initFilter();
        displayEventList(list);
    </script>
</div>