<div class="content container">
    <div class="row">
        <section class="col-sm-8 col-sm-push-2" id="categories">
            <?php
            foreach ($tags as $tag) {
                echo '<section class="col-xs-4">'
                . '<h6><a href="events/tag/' . $tag->getName() . '">'
                . '<img alt="' . $tag->getName() . ' events" src="' . $tag->getImagePath() . '">'
                . $tag->getName()
                . '</a></h6>'
                . '</section>';
            }
            ?>
        </section>
    </div>

    <div class="row">
        <section class="col-sm-12" id="campus">
            <h2>Westerdals Oslo ACT</h2>
            <p>Campus Fjerdingen, Vulkan og Brenneriveien er Westerdals Oslo School of Arts, Communication and Technology sine universitetsområder. Universitetsplassene ligger sentralt i Oslosbykjerne med biblioteker, forelesningssaler, studentboliger og store parkarealer. Westerdals Oslo ACT er en unik og kreativ skole for deg som vil jobbe innen kunst, kommunikasjon eller teknologi. Denne nettsiden vil veilede deg gjennom arrangementer som du kan delta i når du studerer på Westerdals Oslo ACT. Campusene ligger relativt nærme hverandre men er spredt på forskjellige deler av Osloskjerne fra begynnelsen av Grønland til enden av Grünerløkka.<br>
                VI er HER for å gjøre DIN studentopplevelse på campus Fjerdingen, Vulkan eller Brenneriveien FANTASTISK, SPENNENDE og KREATIV! Vi håper du får en fantastisk studentopplevelse på Westerdals Oslo School of Arts, Communication and Technology!
                Kontakt oss gjerne hvis det er noe du lurer på gjennom kontaktforumet vårt.<br><br></p>
        </section>
    </div>
    <div class="row">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1999.9663401250284!2d10.757554815777556!3d59.91610597087856!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46416e6057bf3f39%3A0x22d6a578df0644b5!2sWesterdals+Oslo+ACT!5e0!3m2!1sen!2sno!4v1495841236000" width="100%" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
</div>