<div class="container">
    <div id="passsword-reminder-row" class="row">
        <div class="col-md-6 col-md-offset-3">
            <?php
            if (isset($response)) {
                echo '<div role="alert" class="alert alert-success"><strong>' . $response . '</strong></div>';
            }
            ?>
            <div class="well well-sm <?php
            if (isset($response)) {
                echo ' hide';
            }
            ?>">
                <form class="form-horizontal" method="post" id="form-password-reminder" action="">
                    <fieldset>
                        <legend class="text-center">Glemt passord</legend>

                        <!-- Email input-->
                        <div class="form-group">
                            <label class="col-md-2 control-label" for="email">E-post</label>
                            <div class="col-md-10">
                                <input id="email" name="email" type="email" placeholder="" class="form-control" spellcheck="false" autocomplete="off" autocorrect="off">
                            </div>
                        </div>

                        <!-- Form actions -->
                        <div class="form-group">
                            <div class="col-md-12 text-right">
                                <button type="submit" class="btn btn-success btn-lg" name="submit">Send</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>

            <div id="password-reminder-note" class="row">
                <div class="col-xs-12">
                    <a href="/login" class="loginlink">login</a>
                </div>
            </div>
        </div>
    </div>
</div>