<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="/" />
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" href="css/stylesheet.css">
        <title><?= $title ?></title>
        <script src="js/jquery-2.1.4.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/webb.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"><b>Westerdals</b> <span class="small"> Events</span></a>
                </div>
                <div class="collapse navbar-collapse" id="collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/">Hjem</a></li>
                        <li><a href="event">Arrangementer</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <article>
            <?php $this->controller->renderView(); // renders the current view into the template ?>
        </article>

        <div class="footer">
            <p><a href="contact">Kontakt oss</a>  |  <a href="about">Om oss</a></p>
            <br>
            <p>
                Tlf: <a aria-label="kontakt telefonnummer" href="tel:22057550">22 05 75 50</a><br />
                Epost: <a aria-label="kontakt e-post" href="mailto:post@westerdals.no">post@westerdals.no</a>
            </p><br />
            <p>Opphavsrett © Westerdals 2017</p>
        </div>
    </body>
</html>