<div class="container">
    <div id="registration-row" class="row">
        <div class="col-md-6 col-md-offset-3">
            <?php
            if (isset($response)) {
                echo '<div class="alert alert-success"><strong>' . $response . '</strong></div>';
            }
            ?>
            <div class="well well-sm ">
                <form class="form-horizontal" action="user/registration" method="post">
                    <fieldset>
                        <legend class="text-center">Registrering</legend>

                        <!-- Name input-->
                        <div class="form-group">
                            <label class="col-md-3 control-label" for="name">Navn</label>
                            <div class="col-md-9">
                                <input id="name" name="name" type="text" required placeholder="" class="form-control" spellcheck="false" autocomplete="off" autocorrect="off">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label" for="useranme">Brukernavn</label>
                            <div class="col-md-9">
                                <input id="useranme" name="username" type="text" placeholder="" required class="form-control" spellcheck="false" autocomplete="off" autocorrect="off">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label" for="e-post">E-post</label>
                            <div class="col-md-9">
                                <input id="e-post" name="email" type="text" placeholder="" class="form-control" spellcheck="false" autocomplete="off" autocorrect="off">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label" for="password">Passord</label>
                            <div class="col-md-9">
                                <input id="password" name="password" type="password" placeholder="" required class="form-control" spellcheck="false" autocomplete="off" autocorrect="off">
                            </div>
                        </div>

                        <!--
                        <div class="form-group">
                            <label class="col-md-2 control-label" for="re-password">Repeter passord</label>
                            <div class="col-md-10">
                                <input id="re-password" name="repeatPassword" type="password" placeholder="" required class="form-control" spellcheck="false" autocomplete="off" autocorrect="off">
                            </div>
                        </div>
                        -->

                        <!-- Form actions -->
                        <div class="form-group">
                            <div class="col-md-12 text-right">
                                <button type="submit" class="btn btn-success btn-lg" name="submit">Lag bruker</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>

</div>