<div class="content container">

    <div class="row">
        <div class="col-sx-12 text-left">
            <?php
            $event = $events[0];
            $dateFormat = $event->getDate();
            $dateArr = explode('-', $dateFormat);
            if (is_array($dateArr)) {
                $dateFormat = "{$dateArr[2]}-{$dateArr[1]}-{$dateArr[0]}";
            }
            echo '<section class="single-arrangement-section" id="event-' . $event->getId() . '">'
            . '<div class="cnt">'
            . '<img alt="' . $event->getName() . '" src="' . $event->getImagePath() . '">'
            . '<h2>' . $event->getName() . '</h2>'
            . '<div><strong>Dato:</strong> ' . $dateFormat . '</div>'
            . '<div><strong>Tid:</strong> ' . $event->getTime() . '</div>'
            . '<div><strong>Sted: </strong>' . $event->getLocation()->getAddress() . ', ' . $event->getLocation()->getZipCode() . ' ' . $event->getLocation()->getCity() . '</div>'
            . '<div><strong>Pris:</strong> ' . $event->getPrice() . ' kr</div>'
            . '<div><strong>Arrangør:</strong> ' . $event->getOrganizer()->getName() . '</div>'
            . '<div class="description"> ' . $event->getDescription() . '</div>'
            . '</div>'
            . '<div class="location-map"> ' . $event->getLocation()->getLocationPath() . '</div>'
            . '</section>';
            ?>
        </div>
    </div>

</div>