<?php /*

foreach ($events as $event) {
    echo '<div class="event" id="event-' . $event->getId() . '">'
    . '<h4>' . $event->getName() . '</h4>'
    . '<b>Dato:</b> ' . $event->getDate() . '<br />'
    . '<b>Tid:</b> ' . $event->getTime() . '<br />'
    . '<b>Sted:</b> ' . $event->getLocation() . '<br />'
    . '<b>Pris:</b> ' . $event->getPrice() . '<br />'
    . '<b>Arrangør:</b> ' . $event->getOrganizer()
    . '<p> ' . $event->getDescription() . '</p>'
    . '</div>';
}
*/
?>

<?php require "header.php"?>

    <div class="content container">
    
    <div class="row">
    <section class="col-xs-6 col-xs-push-3" id="search-input">
        <div class="input-group col-xs-12">
            <input type="text" class="form-control input-lg" name="search" placeholder="Search..." />
            <span class="input-group-btn">
                <button class="btn btn-info btn-lg" type="button">
                <i class="glyphicon glyphicon-search"></i>
                </button>
            </span>
        </div>
    </section>
    </div>
        
    <div class="row" id="events">
    <section class="col-sm-4" id="event">
        <a href="#event">
        <img src="../../public/images/COLOURBOX95430431.jpg">
        <h3>Event</h3>
        </a>
        <h6>08.06.2017</h6>
        <h6>kl 12:00-24:00</h6>
        <a href="https://www.google.no/maps/place/Cafe+Sara/@59.9176068,10.7519658,17z/data=!3m1!4b1!4m5!3m4!1s0x46416e66acf2ba6d:0x6e108cf4f57a3db7!8m2!3d59.9176068!4d10.7541491"><h6>Café Sara</h6></a>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus doloribus doloribus doloribus doloribus</p>
    </section>
    <section class="col-sm-4" id="event">
        <a href="#event">
        <img src="../../public/images/COLOURBOX95430431.jpg">
        <h3>Event</h3>
        </a>
        <h6>08.06.2017</h6>
        <h6>kl 12:00-24:00</h6>
        <a href="https://www.google.no/maps/place/Cafe+Sara/@59.9176068,10.7519658,17z/data=!3m1!4b1!4m5!3m4!1s0x46416e66acf2ba6d:0x6e108cf4f57a3db7!8m2!3d59.9176068!4d10.7541491"><h6>Café Sara</h6></a>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus</p>
    </section>
    <section class="col-sm-4" id="event">
        <a href="#event">
        <img src="../../public/images/COLOURBOX95430431.jpg">
        <h3>Event</h3>
        </a>
        <h6>08.06.2017</h6>
        <h6>kl 12:00-24:00</h6>
        <a href="https://www.google.no/maps/place/Cafe+Sara/@59.9176068,10.7519658,17z/data=!3m1!4b1!4m5!3m4!1s0x46416e66acf2ba6d:0x6e108cf4f57a3db7!8m2!3d59.9176068!4d10.7541491"><h6>Café Sara</h6></a>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus</p>
    </section>
    <section class="col-sm-4" id="event">
        <a href="#event">
        <img src="../../public/images/COLOURBOX95430431.jpg">
        <h3>Event</h3>
        </a>
        <h6>08.06.2017</h6>
        <h6>kl 12:00-24:00</h6>
        <a href="https://www.google.no/maps/place/Cafe+Sara/@59.9176068,10.7519658,17z/data=!3m1!4b1!4m5!3m4!1s0x46416e66acf2ba6d:0x6e108cf4f57a3db7!8m2!3d59.9176068!4d10.7541491"><h6>Café Sara</h6></a>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus</p>
    </section>
    <section class="col-sm-4" id="event">
        <a href="#event">
        <img src="../../public/images/COLOURBOX95430431.jpg">
        <h3>Event</h3>
        </a>
        <h6>08.06.2017</h6>
        <h6>kl 12:00-24:00</h6>
        <a href="https://www.google.no/maps/place/Cafe+Sara/@59.9176068,10.7519658,17z/data=!3m1!4b1!4m5!3m4!1s0x46416e66acf2ba6d:0x6e108cf4f57a3db7!8m2!3d59.9176068!4d10.7541491"><h6>Café Sara</h6></a>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus</p>
    </section>
    <section class="col-sm-4" id="event">
        <a href="#event">
        <img src="../../public/images/COLOURBOX95430431.jpg">
        <h3>Event</h3>
        </a>
        <h6>08.06.2017</h6>
        <h6>kl 12:00-24:00</h6>
        <a href="https://www.google.no/maps/place/Cafe+Sara/@59.9176068,10.7519658,17z/data=!3m1!4b1!4m5!3m4!1s0x46416e66acf2ba6d:0x6e108cf4f57a3db7!8m2!3d59.9176068!4d10.7541491"><h6>Café Sara</h6></a>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus</p>
    </section>     
    </div>
    
    </div>

<?php require "footer.php"?>