<?php
/*
foreach ($tags as $tag) {
    echo '<a href="">' . $tag->getName() . '</a><br/>';
}
*/
?>

<?php require 'header.php'?>

    <div class="content container">
    
    <div class="row">
    <section class="col-xs-6 col-xs-push-3" id="search-input">
        <div class="input-group col-xs-12">
            <input type="text" class="form-control input-lg" name="search" placeholder="Search..." />
            <span class="input-group-btn">
                <button class="btn btn-info btn-lg" type="button">
                <i class="glyphicon glyphicon-search"></i>
                </button>
            </span>
        </div>
    </section>
    </div>
    
    <div class="row">
    <section class="col-sm-8 col-sm-push-2" id="categories">
        <section class="col-xs-4">
            <a href="#event">
            <img src="../../public/images/COLOURBOX95430431.jpg">
            <h6>Konserter</h6>
            </a>
        </section>
        <section class="col-xs-4">
            <a href="#event">
            <img src="../../public/images/COLOURBOX95430431.jpg">
            <h6>Festivaler</h6>
            </a>
        </section>
        <section class="col-xs-4">
            <a href="#event">
            <img src="../../public/images/COLOURBOX95430431.jpg">
            <h6>Konkurranser</h6>
            </a>
        </section>
        <section class="col-xs-4">
            <a href="#event">
            <img src="../../public/images/COLOURBOX95430431.jpg">
            <h6>Workshops</h6>
            </a>
        </section>
        <section class="col-xs-4">
            <a href="#event">
            <img src="../../public/images/COLOURBOX95430431.jpg">
            <h6>Forelesninger</h6>
            </a>
        </section>
        <section class="col-xs-4">
            <a href="#event">
            <img src="../../public/images/COLOURBOX95430431.jpg">
            <h6>Utstillinger</h6>
            </a>
        </section>
       </section>
    </div>
    
    <div class="row">
    <section class="col-sm-12" id="campus">
        <h2>Campus</h2>      
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean consequat nunc libero, ac sollicitudin tellus volutpat quis. Nam lobortis, dui ac efficitur molestie, risus lectus convallis enim, a lobortis nibh urna quis tellus. Nunc sed malesuada ligula, eleifend volutpat magna. Integer non lorem nibh. Maecenas sollicitudin ornare ligula, vitae facilisis magna consequat tempus. Aliquam eget posuere est. Phasellus eu auctor lorem. Morbi lacinia efficitur enim non facilisis. Ut tincidunt sit amet eros a efficitur. Donec volutpat diam neque, sed auctor mi scelerisque ut. Praesent lacus nunc, efficitur id sagittis eget, ultricies vitae nunc.</p>

        <p>Nulla fermentum convallis dolor, non facilisis est. Morbi magna lectus, dapibus rutrum metus sit amet, placerat malesuada nibh. Sed in libero nulla. Aliquam lacinia turpis eu odio vehicula vehicula. Praesent volutpat, leo ac dapibus rhoncus, sapien orci porttitor nulla, vitae vestibulum urna odio sed quam. Integer ac aliquet sem, id laoreet diam. Mauris egestas efficitur nulla, nec semper urna bibendum vel. Donec lobortis non velit at pulvinar. Sed condimentum nisl non sollicitudin rhoncus. Aliquam erat volutpat. Proin vulputate, libero vitae ultrices condimentum, nulla dolor placerat neque, nec rutrum turpis mi non nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin commodo, felis nec vehicula pellentesque, tortor elit posuere sem, sit amet tempor dolor arcu a odio.</p>
    </section>
    </div>  
    
    </div>

<?php require "footer.php"?>