<!DOCTYPE html>
<html lang="no">
    <head>
        <base href="/" />
        <meta charset="UTF-8" />
        <title><?= $title ?></title>
        <meta name="description" content="<?= $description ?>" />
        <link rel="stylesheet" href="css/style.css" type="text/css"/>
    </head>

    <body>
        <header>
            <h1>Webb - Westerdal's Event Bulletin Board</h1>
        </header>

        <nav>
            <ul>
                <li><a href="home">Hjem</a></li>
                <li><a href="event">Arrangementer</a></li>
                <li><a href="account">Min konto</a></li>
                <li><a href="contact">Kontakt oss</a></li>
            </ul>
        </nav>
        <br clear="both" />

        <article>
            <?php $this->controller->renderView(); // renders the current view into the template ?>
        </article>

        <footer>
            <p>Opphavsrett © gruppe ?</p>
        </footer>
    </body>
</html>