<?php require "header.php"?>

    <div class="content container">
        
        <div class="row" id="events">
            <section class="col-sm-4 col-sm-push-4" id="event">
                <h2>Navn</h2>
                <br>
                <a href="saved-events"><h5>Lagrede events</h5></a>
                
                <a href="saved-arrangor"><h5>Favorittarrangørers events</h5></a>
                
            </section>
        </div>
    
    </div>

<?php require "footer.php"?>